version: 1.0.{build}-Alpha
os: Visual Studio 2015

cache:
  - '%LocalAppData%\NuGet\Cache'

configuration:
  - Debug
  - Release
  
environment:
  SK_BUILD_CONFIGURATION: $(configuration)

init:
  - git config --global core.autocrlf true

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  - nuget restore SteamKit2\SteamKit2.sln
  - nuget restore Samples\Samples.sln

build_script:
  - msbuild SteamKit2\SteamKit2.sln
  - msbuild Samples\Samples.sln

test_script:
  - ps: >-
      $TestAssembly = "SteamKit2\Tests\Bin\$env:SK_BUILD_CONFIGURATION\Tests.dll"
      
      if (Test-Path $TestAssembly)
      {
          & nuget install OpenCover -Version 4.6.166 -OutputDirectory SteamKit2\packages
          & SteamKit2\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user "-target:xunit.console.clr4.exe" "-targetargs:$TestAssembly /noshadow /appveyor" -returntargetcode "-filter:+[SteamKit2]* -[SteamKit2]SevenZip*" "-excludebyattribute:*.ProtoContract*;*.SteamLanguageGenerated*" -hideskipped:All -output:SteamKit2-code-coverage.xml
          $env:Path = "C:\Python34;C:\Python34\Scripts;" + $env:Path
          & pip install codecov
          & codecov -f "SteamKit2-code-coverage.xml" -X gcov
      }